config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: %i[new create index]
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[create show]
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, length: { in: 5..150 }
end

app/models/user.rb
class User < ApplicationRecord
  before_create :remember_first

  attr_accessor :remember_token
  has_many :posts

  validates :username, presence: true, length: { in: 6..15 }
  validates :email, presence: true, length: { maximum: 40 }, uniqueness: { case_sensitive: false },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze }
  validates :password, presence: true, length: { in: 6..15 }

  has_secure_password

  def digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def remember
    self.remember_token = SecureRandom.urlsafe_base64
    update_attribute(:remember_digest, digest(remember_token))
  end

  def remember_first
    self.remember_token = SecureRandom.urlsafe_base64.to_s
    self.remember_digest = digest(remember_token)
  end

  def forget
    self.remember_token = nil
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :user_logged_in?, only: %i[new create]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 10)
  end

  def new
    @post = Post.new
  end

  def create
    user = session[:user_id]
    @post = Post.new(user_id: user, content: post_params[:content])
    if @post.save
      flash[:success] = 'You succesfully made a new comment'
      redirect_to root_path
    else
      flash[:success] = session[:user_id]
      render 'new'
    end
  end

  def destroy; end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def user_logged_in?
    return nil if logged_in?

    flash[:danger] = 'please loggin before you can comment'
    redirect_to login_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user&.authenticate(params[:session][:password])
      log_in @user
      params[:session][:remember] == '1' ? remember(@user) : forget(@user)
      flash[:success] = 'successfylly logged in'
      redirect_to root_path
    else
      flash[:danger] = 'the email/password pair was incorrect'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      remember @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  private

  def user_params
    params.require(:user).permit(
      :username,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
    @current_user = user
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    elsif cookies.signed[:user_id]
      user = User.find_by(id: cookies.signed[:user_id])
      if user&.authenticated?(cookies[:remember_token])
        @current_user = user
        log_in @current_user
      end
    end
    @current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget current_user
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)# (1)this can also be done:   , size: 80)  
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    # (2)and this:   #{gravatar_id}?s=#{size}"
     image_tag(gravatar_url, alt: user.username, class: "gravatar", size:100)
  end
end

app/views/layouts/_footer.html.erb
<footer>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="logo-wrapper">
    <%= link_to image_tag('logo.svg'), root_path %>
  </div>
  <nav>
    <ul>
      <li><%= link_to 'Home', root_path %></li>
      <% unless logged_in? %>
        <li><%= link_to 'Sign Up', signup_path, class: 'signup' %></li>
        <li><%= link_to 'Log In', login_path, class: 'login' %></li>
      <% else %>
        <li><%= link_to  'logout', logout_path, method: :delete, class: 'login' %></li>
        <li><%= link_to 'post', new_post_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= render  "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render  "layouts/footer" %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="capsule">
  <h2><%= post.user.username if logged_in? %></h2>
  <p><%= post.content %></p>
</div>

app/views/posts/index.html.erb
<div class="main-content">
  <%= render  "shared/feed" %>
</div>

app/views/posts/new.html.erb
<%= render  "shared/error_messages", new_sub: @post %>
<%= form_for @post do |f| %>
  <%= f.label :content, "content" %>
  <%= f.text_area :content %>
  <%= f.submit 'Send post' %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if new_sub&.errors.count > 0 %>
  <% new_sub.errors.full_messages.each do |error| %>
    <span><%= error %></span>
  <% end %>
<% end %>

app/views/shared/_feed.html.erb
<div class="feed">
  <%= will_paginate @posts %>
  <%= render  @posts %>
</div>

app/views/users/_user.html.erb
<div class="capsule">
  <%= user.id.to_s + '.- ' + user.username %>
</div>

app/views/users/create.html.erb
<h1><%= params %></h1>

app/views/users/edit.html.erb
<%= render  "shared/error_messages", new_sub: @user %>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<%= will_paginate @users %>
<%= render @users %>

app/views/users/new.html.erb
<%= render  "shared/error_messages", new_sub: @user %>

<%= form_for @user do |f| %>
<%= f.label :username, "Username" %>
<%= f.text_field :username %>
<%= f.label :email, "Email" %>
<%= f.email_field :email %>
<%= f.label :password, "password" %>
<%= f.password_field :password %>
<%= f.label :password_confirmation, "password confirmation" %>
<%= f.password_field :password_confirmation %>
<%= f.submit 'submit now' %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<h1><%= @user.email %></h1>